# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Check for broken links

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.98.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Refresh modules
        run: |
          hugo mod get -u ./...
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo
      - name: Upload folder artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./public

  # Check broken links job
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./public
      - name: List files
        run: |
          ls -R
      - name: Check HTML with HTMLTest
        uses: wjdp/htmltest-action@master
        with:
          config: ./public/artifact/.htmltest.yml
      #- name: Check HTML with HTMLProofer
      #  uses: chabad360/htmlproofer@master
      #  with:
      #    directory: ./public
